In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Split data into train and test data
from sklearn.model_selection import train_test_split

# Preprocessing:
from sklearn.preprocessing import StandardScaler

# Import class DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier as dtree

# To draw decision tree
from sklearn.tree import export_graphviz
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
from sklearn.tree import export_graphviz


from sklearn.datasets import load_iris
import os
from sklearn.model_selection import train_test_split

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

In [11]:
df =  pd.read_csv('diabetes_data_upload.csv')

In [4]:
df.head(3)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive

In [5]:
df.head(-3)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,43,Male,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,Negative
513,62,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,Yes,Positive
514,54,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive

In [6]:
df.tail(3)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

In [8]:
df.describe()

              Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [9]:
df.size()

TypeError: 'numpy.int32' object is not callable

In [10]:
df.size

8840

In [12]:
bmi = pd.read_csv('bmi.csv')

In [13]:
bmi.head(3)

   BMI
0   25
1   35
2   19

In [14]:
bmi.tail(3)

     BMI
517   39
518   23
519   23

In [15]:
bmi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   BMI     520 non-null    int64
dtypes: int64(1)
memory usage: 4.2 KB

In [16]:
df ['bmi'] = bmi
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,bmi
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,25
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,35
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,19
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,21
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,31

In [17]:
df.isna().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
bmi                   0
dtype: int64

In [19]:
df ['Age_Cat'] = pd.cut(x = df['Age'], bins = [1,55, 100], labels = ['Youngster','Aged'])

In [20]:
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,bmi,Age_Cat
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,25,Youngster
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,35,Aged
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,19,Youngster
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,21,Youngster
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,31,Aged

In [21]:
df_C = df

In [23]:
df_C = df_C.drop(['Age'], axis = 1)

In [24]:
df_C.head()

,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,bmi,Age_Cat
0,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,25,Youngster
1,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,35,Aged
2,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,19,Youngster
3,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,21,Youngster
4,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,31,Aged

In [32]:
df_C['Gender'] = df_C['Gender'].replace({'Male' : 1, 'Female' : 0})
df_C['Polyuria'] = df_C['Polyuria'].replace({'Yes' : 1, 'No' : 0})
df_C['Polydipsia'] = df_C['Polydipsia'].replace({'Yes' : 1, 'No' : 0})
df_C['sudden weight loss'] = df_C['sudden weight loss'].replace({'Yes' : 1, 'No' : 0})
df_C['weakness'] = df_C['weakness'].replace({'Yes' : 1, 'No' : 0})
df_C['Polyphagia'] = df_C['Polyphagia'].replace({'Yes' : 1, 'No' : 0})
df_C['Genital thrush'] = df_C['Genital thrush'].replace({'Yes' : 1, 'No' : 0})
df_C['Genital thrush'] = df_C['Genital thrush'].replace({'Yes' : 1, 'No' : 0})
df_C['visual blurring'] = df_C['visual blurring'].replace({'Yes' : 1, 'No' : 0})
df_C['Itching'] = df_C['Itching'].replace({'Yes' : 1, 'No' : 0})
df_C['Irritability'] = df_C['Irritability'].replace({'Yes' : 1, 'No' : 0})
df_C['delayed healing'] = df_C['delayed healing'].replace({'Yes' : 1, 'No' : 0})
df_C['partial paresis'] = df_C['partial paresis'].replace({'Yes' : 1, 'No' : 0})
df_C['muscle stiffness'] = df_C['muscle stiffness'].replace({'Yes' : 1, 'No' : 0})
df_C['Alopecia'] = df_C['Alopecia'].replace({'Yes' : 1, 'No' : 0})
df_C['Obesity'] = df_C['Obesity'].replace({'Yes' : 1, 'No' : 0})
df_C['class'] = df_C['class'].replace({'Positve' : 1, 'Negative' : 0})
df_C['Age_Cat'] = df_C['Age_Cat'].replace({'Youngster' : 1, 'Aged' : 0})

In [33]:
df_C.head()

,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,bmi,Age_Cat,class\t
0,1,0,1,0,1,0,0,0,1,0,1,0,1,1,1,Positive,25,1,Positive
1,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,Positive,35,0,Positive
2,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,Positive,19,1,Positive
3,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,Positive,21,1,Positive
4,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,Positive,31,0,Positive